### ISSUE TITLE
UI Enhacement and Update To 2.10.5

### ISSUE THREAD

**Issue by pnkr01** [ArizArmeidi/FlutterWeather#3]
![c](https://user-images.githubusercontent.com/83778936/171188872-19819e4e-0ec9-4cbc-8443-e1cc3fcfbb80.png)
![a](https://user-images.githubusercontent.com/83778936/171188889-c0d2b828-7e69-4888-94c1-01a053a3ae99.png)
![b](https://user-images.githubusercontent.com/83778936/171188895-37db6a01-883c-40be-8856-ad1c1b31ac3a.png)

**Comment by felipe1almeida** [comment]
Is this project still active?
The idea is to update the screens as they are in the print above?

**Comment by ArizArmeidi** [comment]
Sorry currently busy with work and can't keep up with my side project, still planning to update all of my side projects code. hopefully I have time around the end of this year to do it

**Comment by felipe1almeida** [comment]
yeah, no worries.
if you want help, you can count on me
