### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by IanDarwin** [ArizArmeidi/FlutterWeather#6]
Running on a Pixel 6A with poor internet connectivity where I am, and with Location allowed "while using App", it just crashes.
The UI goes straight to reporting "No search results"...
When I press Return Home, it shows the search box briefly but not long enough to type anything (can't even type a few letters), then goes back to No Search Results. 
Loop ad nauseum.

I did put my OWM API key in place :-) 'git diff' shows that the only change, from 09918c1a79fd

$ flutter run
. . .
💪 Running with sound null safety 💪

An Observatory debugger and profiler on Pixel 6a is available at: http://127.0.0.1:4156/74dQjtPQmp4=/
I/flutter_weather(11763): Compiler allocated 4579KB to compile void android.view.ViewRootImpl.performTraversals()
The Flutter DevTools debugger and profiler on Pixel 6a is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:4156/74dQjtPQmp4=/
E/SurfaceSyncer(11763): Failed to find sync for id=0
D/CompatibilityChangeReporter(11763): Compat change id reported: 78294732; UID 10306; state: DISABLED
I/flutter (11763): NoSuchMethodError: The method '[]' was called on null.
I/flutter (11763): Receiver: null
I/flutter (11763): Tried calling: [](0)
E/flutter (11763): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (11763): Receiver: null
E/flutter (11763): Tried calling: [](0)
E/flutter (11763): #0      WeatherProvider.getDailyWeather (package:flutter_weather/provider/weatherProvider.dart:105:7)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #1      WeatherProvider.getWeatherData.<anonymous closure> (package:flutter_weather/provider/weatherProvider.dart:36:11)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #2      WeatherProvider.getWeatherData (package:flutter_weather/provider/weatherProvider.dart:30:5)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763):
I/flutter (11763): NoSuchMethodError: The method '[]' was called on null.
I/flutter (11763): Receiver: null
I/flutter (11763): Tried calling: [](0)
E/flutter (11763): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (11763): Receiver: null
E/flutter (11763): Tried calling: [](0)
E/flutter (11763): #0      WeatherProvider.getDailyWeather (package:flutter_weather/provider/weatherProvider.dart:105:7)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #1      WeatherProvider.getWeatherData.<anonymous closure> (package:flutter_weather/provider/weatherProvider.dart:36:11)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763): #2      WeatherProvider.getWeatherData (package:flutter_weather/provider/weatherProvider.dart:30:5)
E/flutter (11763): <asynchronous suspension>
E/flutter (11763):

Installing the obvious "if-null check print; return" at line 36 just makes it crash further down.

Thoughts?

**Comment by ArizArmeidi** [comment]
Thank you for submitting this, I already tested on my pixel 6A but only with a normal internet connection and I can't replicate this error. I'll try to investigate further when I have free time

**Comment by ArizArmeidi** [comment]
fixed on 03cd5c07afa73666c37fb2fb2c00f66df8c35c60
