### ISSUE TITLE
getDailyWeather uses the previous location

### ISSUE THREAD

**Issue by jimbeers** [ArizArmeidi/FlutterWeather#7]
If I'm reading this correctly, in weatherProvider.dart, in searchweather, 
the code is saving the latitude, and longitude, then calls searchweatherWithLocation, which sets the weather object that has been entered in the searchBar.dart.
Then calls getDailyweather, which uses the lat and long from before searchWeatherWithLocation was called, so it is the previous location.
simply moving the code around fixes this,
// first call this with will set the weather object
    _await searchWeatherWithLocation(location);_
// then get that lat and long, 
    double latitude = weather.lat;
    double longitude = weather.long;

    await getDailyWeather(LatLng(latitude, longitude));

**Comment by ArizArmeidi** [comment]
I'm planning to update the logic part of this app. I coded this when I first started Flutter so some of it still kinda messy and buggy. will update this soon when I have the time

**Comment by ArizArmeidi** [comment]
fixed on 03cd5c07afa73666c37fb2fb2c00f66df8c35c60
